services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    volumes:
      - ./dbdata:/var/lib/mysql/